version: "3.3"
services:
  scheduler:
    image: dask_gdal  
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
  worker1:
    image: dask_gdal
    ports:
      - "7722:22"    
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]
  worker2:
    image: dask_gdal
    ports:
      - "7723:22"     
    hostname: dask-worker2
    command: ["dask-worker", "tcp://scheduler:8786"]    
  worker3:
    image: dask_gdal
    ports:
      - "7724:22" 
    hostname: dask-worker3
    command: ["dask-worker", "tcp://scheduler:8786"]    
  worker4:
    image: dask_gdal
    ports:
      - "7725:22" 
    hostname: dask-worker4
    command: ["dask-worker", "tcp://scheduler:8786"] 
  notebook:
    image: daskdev/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
      - EXTRA_APT_PACKAGES=gdal-bin libgdal-dev
      - EXTRA_CONDA_PACKAGES=rasterio
  prefect:
    image: dask_gdal
    hostname: prefect
    tty: true
    ports:
      - 8080:8080
